compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: /path/RL_Heals_SFT/scripts/ds_stage3.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: ''
main_process_port: 22222
main_training_function: main
num_machines: 4
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
